### ISSUE TITLE
Docs: Command line options changed vs. documentation

### ISSUE THREAD

**Issue by cteodor** [endgameinc/eqllib#1]
The option --source is no longer there, and -f is gone as well.

Example in docs:
eqllib query -f my-sysmon-data.json --source "Microsoft Sysmon" "process where process_name in ('ipconfig.exe', 'netstat.exe', 'systeminfo.exe', 'route.exe')"

Actual working:
eqllib query -s 'Microsoft Sysmon' "process where process_name in ('ipconfig.exe', 'netstat.exe', 'systeminfo.exe', 'route.exe')"

**Comment by rw-access** [comment]
Thanks @cteodor.
We just pushed an update b477d2bb440bf5f2cad5a9fe274b2aa7f6cacebe that added a few things, including `--source` back. Does that resolve this issue?
